"""Add the pgvector-backed M4.1 memory foundation.

Revision ID: 0012_memory_foundation
Revises: 0011_factions_time
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0012_memory_foundation"
down_revision: str | None = "0011_factions_time"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        DO $$
        DECLARE
            installed_vector_version text;
        BEGIN
            IF current_setting('server_version_num')::integer < 180000 THEN
                RAISE EXCEPTION 'M4.1 requires PostgreSQL 18 or newer';
            END IF;

            SELECT extversion INTO installed_vector_version
            FROM pg_extension
            WHERE extname = 'vector';

            IF installed_vector_version IS DISTINCT FROM '0.8.6' THEN
                RAISE EXCEPTION
                    'M4.1 requires vector extension 0.8.6; found %',
                    COALESCE(installed_vector_version, 'absent');
            END IF;
        END;
        $$
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory_embedding_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_key", sa.String(length=80), nullable=False),
        sa.Column("provider_kind", sa.String(length=30), nullable=False),
        sa.Column("model_name", sa.String(length=160), nullable=False),
        sa.Column("model_revision", sa.String(length=120), nullable=False),
        sa.Column("artifact_sha256", sa.String(length=64), nullable=False),
        sa.Column("license_id", sa.String(length=80), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("normalization", sa.String(length=20), nullable=False),
        sa.Column("distance_metric", sa.String(length=20), nullable=False),
        sa.Column("adapter_version", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "artifact_sha256 ~ '^[0-9a-f]{64}$'", name="memory_profile_artifact_sha256"
        ),
        sa.CheckConstraint("distance_metric = 'cosine'", name="memory_profile_distance_metric"),
        sa.CheckConstraint("normalization IN ('none', 'l2')", name="memory_profile_normalization"),
        sa.CheckConstraint(
            "profile_key ~ '^[a-z0-9][a-z0-9._-]{0,79}$'", name="memory_profile_key_format"
        ),
        sa.CheckConstraint(
            "provider_kind IN ('deterministic', 'local_onnx')", name="memory_profile_provider_kind"
        ),
        sa.CheckConstraint("dimensions BETWEEN 1 AND 4096", name="memory_profile_dimensions"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_key"),
    )
    op.create_table(
        "campaign_memory_indexes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("indexed_through_event_sequence", sa.Integer(), nullable=True),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=80), nullable=True),
        sa.Column("last_error_detail", sa.Text(), nullable=True),
        sa.Column("quality_gate", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'active' AND activated_at IS NOT NULL "
            "AND quality_gate IS NOT NULL) OR "
            "(status <> 'active' AND activated_at IS NULL)",
            name="campaign_memory_index_activation_shape",
        ),
        sa.CheckConstraint(
            "(status = 'failed' AND last_error_code IS NOT NULL) OR "
            "(status <> 'failed' AND last_error_code IS NULL "
            "AND last_error_detail IS NULL)",
            name="campaign_memory_index_error_shape",
        ),
        sa.CheckConstraint(
            "status IN ('building', 'ready', 'active', 'failed', 'retired')",
            name="campaign_memory_index_status",
        ),
        sa.CheckConstraint(
            "indexed_through_event_sequence IS NULL OR indexed_through_event_sequence >= 0",
            name="campaign_memory_index_sequence_nonnegative",
        ),
        sa.CheckConstraint("source_count >= 0", name="campaign_memory_index_source_count"),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["memory_embedding_profiles.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", "profile_id", name="uq_campaign_memory_index_profile"),
    )
    op.create_index(
        op.f("ix_campaign_memory_indexes_campaign_id"),
        "campaign_memory_indexes",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaign_memory_indexes_profile_id"),
        "campaign_memory_indexes",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        "uq_campaign_memory_indexes_one_active",
        "campaign_memory_indexes",
        ["campaign_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "memory_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("source_kind", sa.String(length=20), nullable=False),
        sa.Column("source_turn_id", sa.UUID(), nullable=True),
        sa.Column("source_event_id", sa.UUID(), nullable=True),
        sa.Column("source_version", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("event_sequence_start", sa.Integer(), nullable=False),
        sa.Column("event_sequence_end", sa.Integer(), nullable=False),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("chunker_version", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source_world_revision", sa.Integer(), nullable=True),
        sa.Column("source_time_minutes", sa.Integer(), nullable=True),
        sa.Column("location_id", sa.UUID(), nullable=True),
        sa.Column("npc_id", sa.UUID(), nullable=True),
        sa.Column("character_id", sa.UUID(), nullable=True),
        sa.Column("quest_id", sa.UUID(), nullable=True),
        sa.Column("decision_id", sa.UUID(), nullable=True),
        sa.Column("faction_id", sa.UUID(), nullable=True),
        sa.Column("superseded_by_document_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(source_kind = 'turn' AND source_turn_id IS NOT NULL "
            "AND source_event_id IS NULL) OR "
            "(source_kind = 'event' AND source_event_id IS NOT NULL "
            "AND source_turn_id IS NULL)",
            name="memory_document_source_shape",
        ),
        sa.CheckConstraint(
            "(status = 'active' AND superseded_by_document_id IS NULL) OR "
            "(status = 'superseded' AND superseded_by_document_id IS NOT NULL)",
            name="memory_document_supersession_shape",
        ),
        sa.CheckConstraint(
            "content_sha256 ~ '^[0-9a-f]{64}$'", name="memory_document_content_sha256"
        ),
        sa.CheckConstraint("status IN ('active', 'superseded')", name="memory_document_status"),
        sa.CheckConstraint("visibility = 'player'", name="memory_document_player_visible"),
        sa.CheckConstraint(
            "char_length(content) BETWEEN 1 AND 6000", name="memory_document_content_length"
        ),
        sa.CheckConstraint("chunk_index >= 0", name="memory_document_chunk_index_nonnegative"),
        sa.CheckConstraint(
            "event_sequence_start > 0 AND event_sequence_end >= event_sequence_start",
            name="memory_document_event_sequence_range",
        ),
        sa.CheckConstraint(
            "source_time_minutes IS NULL OR source_time_minutes >= 0",
            name="memory_document_time_nonnegative",
        ),
        sa.CheckConstraint("source_version > 0", name="memory_document_source_version_positive"),
        sa.CheckConstraint(
            "source_world_revision IS NULL OR source_world_revision >= 0",
            name="memory_document_world_revision_nonnegative",
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["decision_id"], ["decision_points.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["faction_id"], ["factions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["npc_id"], ["npcs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["quest_id"], ["quests.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_event_id"], ["campaign_events.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_turn_id"], ["turns.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["superseded_by_document_id"], ["memory_documents.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("superseded_by_document_id"),
    )
    op.create_index(
        "ix_memory_documents_campaign_active_sequence",
        "memory_documents",
        ["campaign_id", "event_sequence_end"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        op.f("ix_memory_documents_campaign_id"), "memory_documents", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_documents_character_id"), "memory_documents", ["character_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_documents_decision_id"), "memory_documents", ["decision_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_documents_faction_id"), "memory_documents", ["faction_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_documents_location_id"), "memory_documents", ["location_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_documents_npc_id"), "memory_documents", ["npc_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_documents_quest_id"), "memory_documents", ["quest_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_documents_source_event_id"),
        "memory_documents",
        ["source_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_documents_source_turn_id"),
        "memory_documents",
        ["source_turn_id"],
        unique=False,
    )
    op.create_index(
        "uq_memory_documents_event_version_chunk",
        "memory_documents",
        ["campaign_id", "source_event_id", "source_version", "chunk_index"],
        unique=True,
        postgresql_where=sa.text("source_kind = 'event'"),
    )
    op.create_index(
        "uq_memory_documents_turn_version_chunk",
        "memory_documents",
        ["campaign_id", "source_turn_id", "source_version", "chunk_index"],
        unique=True,
        postgresql_where=sa.text("source_kind = 'turn'"),
    )
    op.create_table(
        "memory_retrievals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("turn_id", sa.UUID(), nullable=True),
        sa.Column("provider_call_id", sa.UUID(), nullable=True),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("ranking_policy", sa.String(length=60), nullable=False),
        sa.Column("query_source_sha256", sa.String(length=64), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requested_count", sa.Integer(), nullable=False),
        sa.Column("returned_count", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("context_budget_chars", sa.Integer(), nullable=False),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'succeeded' AND error_code IS NULL) OR "
            "(status = 'failed' AND error_code IS NOT NULL AND returned_count = 0)",
            name="memory_retrieval_result_shape",
        ),
        sa.CheckConstraint(
            "query_source_sha256 ~ '^[0-9a-f]{64}$'", name="memory_retrieval_query_source_sha256"
        ),
        sa.CheckConstraint(
            "context_budget_chars BETWEEN 1 AND 24000", name="memory_retrieval_context_budget"
        ),
        sa.CheckConstraint("latency_ms >= 0", name="memory_retrieval_latency_nonnegative"),
        sa.CheckConstraint(
            "requested_count BETWEEN 1 AND 50 AND returned_count BETWEEN 0 AND requested_count",
            name="memory_retrieval_count_bounds",
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["memory_embedding_profiles.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["provider_call_id"], ["provider_calls.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["turn_id"], ["turns.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_retrievals_campaign_id"), "memory_retrievals", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_retrievals_profile_id"), "memory_retrievals", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_retrievals_provider_call_id"),
        "memory_retrievals",
        ["provider_call_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_retrievals_turn_id"), "memory_retrievals", ["turn_id"], unique=False
    )
    op.create_table(
        "memory_embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("document_sha256", sa.String(length=64), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
        sa.Column(
            "embedded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "document_sha256 ~ '^[0-9a-f]{64}$'", name="memory_embedding_document_sha256"
        ),
        sa.ForeignKeyConstraint(["document_id"], ["memory_documents.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["memory_embedding_profiles.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id", "profile_id", name="uq_memory_embeddings_document_profile"
        ),
    )
    op.create_index(
        op.f("ix_memory_embeddings_document_id"), "memory_embeddings", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_embeddings_profile_id"), "memory_embeddings", ["profile_id"], unique=False
    )
    op.create_table(
        "memory_index_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=120), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'claimed' AND lease_owner IS NOT NULL "
            "AND lease_expires_at IS NOT NULL AND error_code IS NULL "
            "AND error_detail IS NULL) OR "
            "(status = 'failed' AND lease_owner IS NULL AND lease_expires_at IS NULL "
            "AND error_code IS NOT NULL) OR "
            "(status IN ('pending', 'complete') AND lease_owner IS NULL "
            "AND lease_expires_at IS NULL AND error_code IS NULL "
            "AND error_detail IS NULL)",
            name="memory_index_job_state_shape",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'claimed', 'complete', 'failed')", name="memory_index_job_status"
        ),
        sa.CheckConstraint("attempt_count >= 0", name="memory_index_job_attempt_count"),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["memory_documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["memory_embedding_profiles.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id", "profile_id", name="uq_memory_index_jobs_document_profile"
        ),
    )
    op.create_index(
        op.f("ix_memory_index_jobs_campaign_id"), "memory_index_jobs", ["campaign_id"], unique=False
    )
    op.create_index(
        "ix_memory_index_jobs_claim",
        "memory_index_jobs",
        ["status", "next_attempt_at", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_index_jobs_document_id"), "memory_index_jobs", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_index_jobs_profile_id"), "memory_index_jobs", ["profile_id"], unique=False
    )
    op.create_table(
        "memory_retrieval_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("retrieval_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("semantic_score", sa.Float(), nullable=True),
        sa.Column("lexical_score", sa.Float(), nullable=True),
        sa.Column("recency_score", sa.Float(), nullable=False),
        sa.Column("entity_score", sa.Float(), nullable=False),
        sa.Column("combined_score", sa.Float(), nullable=False),
        sa.Column("selected_chars", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rank BETWEEN 1 AND 50", name="memory_retrieval_item_rank"),
        sa.CheckConstraint(
            "recency_score >= 0 AND entity_score >= 0 AND combined_score >= 0",
            name="memory_retrieval_item_score_nonnegative",
        ),
        sa.CheckConstraint(
            "selected_chars BETWEEN 1 AND 6000", name="memory_retrieval_item_selected_chars"
        ),
        sa.CheckConstraint(
            "semantic_score IS NOT NULL OR lexical_score IS NOT NULL",
            name="memory_retrieval_item_candidate_score",
        ),
        sa.ForeignKeyConstraint(["document_id"], ["memory_documents.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["retrieval_id"], ["memory_retrievals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "retrieval_id", "document_id", name="uq_memory_retrieval_items_document"
        ),
        sa.UniqueConstraint("retrieval_id", "rank", name="uq_memory_retrieval_items_rank"),
    )
    op.create_index(
        op.f("ix_memory_retrieval_items_document_id"),
        "memory_retrieval_items",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memory_retrieval_items_retrieval_id"),
        "memory_retrieval_items",
        ["retrieval_id"],
        unique=False,
    )
    op.execute(
        """
        CREATE FUNCTION gandalfdnd_validate_memory_document_scope()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NEW.source_kind = 'turn' AND NOT EXISTS (
                SELECT 1 FROM turns
                WHERE id = NEW.source_turn_id AND campaign_id = NEW.campaign_id
            ) THEN
                RAISE EXCEPTION 'memory document turn must belong to its campaign';
            END IF;
            IF NEW.source_kind = 'event' AND NOT EXISTS (
                SELECT 1 FROM campaign_events
                WHERE id = NEW.source_event_id AND campaign_id = NEW.campaign_id
            ) THEN
                RAISE EXCEPTION 'memory document event must belong to its campaign';
            END IF;
            IF NEW.location_id IS NOT NULL AND NOT EXISTS (
                SELECT 1 FROM locations
                WHERE id = NEW.location_id AND campaign_id = NEW.campaign_id
            ) THEN
                RAISE EXCEPTION 'memory document location must belong to its campaign';
            END IF;
            IF NEW.npc_id IS NOT NULL AND NOT EXISTS (
                SELECT 1 FROM npcs WHERE id = NEW.npc_id AND campaign_id = NEW.campaign_id
            ) THEN
                RAISE EXCEPTION 'memory document NPC must belong to its campaign';
            END IF;
            IF NEW.character_id IS NOT NULL AND NOT EXISTS (
                SELECT 1 FROM characters
                WHERE id = NEW.character_id AND campaign_id = NEW.campaign_id
            ) THEN
                RAISE EXCEPTION 'memory document character must belong to its campaign';
            END IF;
            IF NEW.quest_id IS NOT NULL AND NOT EXISTS (
                SELECT 1 FROM quests WHERE id = NEW.quest_id AND campaign_id = NEW.campaign_id
            ) THEN
                RAISE EXCEPTION 'memory document quest must belong to its campaign';
            END IF;
            IF NEW.decision_id IS NOT NULL AND NOT EXISTS (
                SELECT 1 FROM decision_points
                WHERE id = NEW.decision_id AND campaign_id = NEW.campaign_id
            ) THEN
                RAISE EXCEPTION 'memory document decision must belong to its campaign';
            END IF;
            IF NEW.faction_id IS NOT NULL AND NOT EXISTS (
                SELECT 1 FROM factions WHERE id = NEW.faction_id AND campaign_id = NEW.campaign_id
            ) THEN
                RAISE EXCEPTION 'memory document faction must belong to its campaign';
            END IF;
            IF NEW.superseded_by_document_id = NEW.id THEN
                RAISE EXCEPTION 'memory document cannot supersede itself';
            END IF;
            IF NEW.superseded_by_document_id IS NOT NULL AND NOT EXISTS (
                SELECT 1 FROM memory_documents
                WHERE id = NEW.superseded_by_document_id
                  AND campaign_id = NEW.campaign_id
                  AND status = 'active'
            ) THEN
                RAISE EXCEPTION 'replacement memory document must be active in the same campaign';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER memory_documents_scope
        BEFORE INSERT OR UPDATE ON memory_documents
        FOR EACH ROW EXECUTE FUNCTION gandalfdnd_validate_memory_document_scope()
        """
    )
    op.execute(
        """
        CREATE FUNCTION gandalfdnd_protect_memory_document_content()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'memory documents cannot be deleted';
            END IF;
            IF ROW(
                OLD.campaign_id, OLD.source_kind, OLD.source_turn_id, OLD.source_event_id,
                OLD.source_version, OLD.chunk_index, OLD.event_sequence_start,
                OLD.event_sequence_end, OLD.visibility, OLD.content, OLD.content_sha256,
                OLD.chunker_version, OLD.source_world_revision, OLD.source_time_minutes,
                OLD.location_id, OLD.npc_id, OLD.character_id, OLD.quest_id,
                OLD.decision_id, OLD.faction_id, OLD.created_at
            ) IS DISTINCT FROM ROW(
                NEW.campaign_id, NEW.source_kind, NEW.source_turn_id, NEW.source_event_id,
                NEW.source_version, NEW.chunk_index, NEW.event_sequence_start,
                NEW.event_sequence_end, NEW.visibility, NEW.content, NEW.content_sha256,
                NEW.chunker_version, NEW.source_world_revision, NEW.source_time_minutes,
                NEW.location_id, NEW.npc_id, NEW.character_id, NEW.quest_id,
                NEW.decision_id, NEW.faction_id, NEW.created_at
            ) THEN
                RAISE EXCEPTION 'memory document source and content are immutable';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER memory_documents_immutable_content
        BEFORE UPDATE OR DELETE ON memory_documents
        FOR EACH ROW EXECUTE FUNCTION gandalfdnd_protect_memory_document_content()
        """
    )
    op.execute(
        """
        CREATE FUNCTION gandalfdnd_validate_memory_embedding()
        RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE
            expected_dimensions integer;
            expected_hash text;
        BEGIN
            SELECT dimensions INTO expected_dimensions
            FROM memory_embedding_profiles WHERE id = NEW.profile_id;
            SELECT content_sha256 INTO expected_hash
            FROM memory_documents WHERE id = NEW.document_id;

            IF expected_dimensions IS NULL OR expected_hash IS NULL THEN
                RAISE EXCEPTION 'memory embedding references an unknown profile or document';
            END IF;
            IF NEW.document_sha256 IS DISTINCT FROM expected_hash THEN
                RAISE EXCEPTION 'memory embedding document hash mismatch';
            END IF;
            IF vector_dims(NEW.embedding) IS DISTINCT FROM expected_dimensions THEN
                RAISE EXCEPTION 'memory embedding dimension mismatch: expected %, found %',
                    expected_dimensions, vector_dims(NEW.embedding);
            END IF;
            IF NEW.embedding::text ~ '(NaN|Infinity)' THEN
                RAISE EXCEPTION 'memory embedding values must be finite';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER memory_embeddings_validate
        BEFORE INSERT OR UPDATE ON memory_embeddings
        FOR EACH ROW EXECUTE FUNCTION gandalfdnd_validate_memory_embedding()
        """
    )
    op.execute(
        """
        CREATE FUNCTION gandalfdnd_prevent_memory_audit_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION '% is immutable', TG_TABLE_NAME;
        END;
        $$
        """
    )
    for table in (
        "memory_embedding_profiles",
        "memory_embeddings",
        "memory_retrievals",
        "memory_retrieval_items",
    ):
        op.execute(
            f"""
            CREATE TRIGGER {table}_immutable
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION gandalfdnd_prevent_memory_audit_mutation()
            """
        )
    op.execute(
        """
        CREATE FUNCTION gandalfdnd_validate_memory_job_scope()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM memory_documents
                WHERE id = NEW.document_id AND campaign_id = NEW.campaign_id
            ) THEN
                RAISE EXCEPTION 'memory index job document must belong to its campaign';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER memory_index_jobs_scope
        BEFORE INSERT OR UPDATE ON memory_index_jobs
        FOR EACH ROW EXECUTE FUNCTION gandalfdnd_validate_memory_job_scope()
        """
    )
    op.execute(
        """
        CREATE FUNCTION gandalfdnd_protect_campaign_memory_index_identity()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION '% cannot be deleted', TG_TABLE_NAME;
            END IF;
            IF ROW(
                OLD.campaign_id, OLD.profile_id, OLD.created_at
            ) IS DISTINCT FROM ROW(
                NEW.campaign_id, NEW.profile_id, NEW.created_at
            ) THEN
                RAISE EXCEPTION 'campaign memory index identity is immutable';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE FUNCTION gandalfdnd_protect_memory_index_job_identity()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION '% cannot be deleted', TG_TABLE_NAME;
            END IF;
            IF ROW(
                OLD.campaign_id, OLD.document_id, OLD.profile_id, OLD.created_at
            ) IS DISTINCT FROM ROW(
                NEW.campaign_id, NEW.document_id, NEW.profile_id, NEW.created_at
            ) THEN
                RAISE EXCEPTION 'memory index job identity is immutable';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER campaign_memory_indexes_identity_immutable
        BEFORE UPDATE OR DELETE ON campaign_memory_indexes
        FOR EACH ROW EXECUTE FUNCTION gandalfdnd_protect_campaign_memory_index_identity()
        """
    )
    op.execute(
        """
        CREATE TRIGGER memory_index_jobs_identity_immutable
        BEFORE UPDATE OR DELETE ON memory_index_jobs
        FOR EACH ROW EXECUTE FUNCTION gandalfdnd_protect_memory_index_job_identity()
        """
    )
    op.execute(
        """
        CREATE FUNCTION gandalfdnd_validate_memory_retrieval_scope()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NEW.turn_id IS NOT NULL AND NOT EXISTS (
                SELECT 1 FROM turns WHERE id = NEW.turn_id AND campaign_id = NEW.campaign_id
            ) THEN
                RAISE EXCEPTION 'memory retrieval turn must belong to its campaign';
            END IF;
            IF NEW.provider_call_id IS NOT NULL AND NOT EXISTS (
                SELECT 1 FROM provider_calls
                WHERE id = NEW.provider_call_id AND campaign_id = NEW.campaign_id
            ) THEN
                RAISE EXCEPTION 'memory retrieval provider call must belong to its campaign';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER memory_retrievals_scope
        BEFORE INSERT ON memory_retrievals
        FOR EACH ROW EXECUTE FUNCTION gandalfdnd_validate_memory_retrieval_scope()
        """
    )
    op.execute(
        """
        CREATE FUNCTION gandalfdnd_validate_memory_retrieval_item_scope()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM memory_retrievals retrieval
                JOIN memory_documents document
                  ON document.campaign_id = retrieval.campaign_id
                WHERE retrieval.id = NEW.retrieval_id
                  AND document.id = NEW.document_id
                  AND document.visibility = 'player'
            ) THEN
                RAISE EXCEPTION
                    'memory retrieval item document must be player-visible in its campaign';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER memory_retrieval_items_scope
        BEFORE INSERT ON memory_retrieval_items
        FOR EACH ROW EXECUTE FUNCTION gandalfdnd_validate_memory_retrieval_item_scope()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM memory_embedding_profiles)
               OR EXISTS (SELECT 1 FROM memory_documents)
               OR EXISTS (SELECT 1 FROM campaign_memory_indexes)
               OR EXISTS (SELECT 1 FROM memory_index_jobs)
               OR EXISTS (SELECT 1 FROM memory_retrievals) THEN
                RAISE EXCEPTION 'Cannot downgrade after M4.1 memory data has been recorded';
            END IF;
        END;
        $$
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER memory_retrieval_items_scope ON memory_retrieval_items")
    op.execute("DROP TRIGGER memory_retrieval_items_immutable ON memory_retrieval_items")
    op.execute("DROP TRIGGER memory_retrievals_scope ON memory_retrievals")
    op.execute("DROP TRIGGER memory_retrievals_immutable ON memory_retrievals")
    op.execute("DROP TRIGGER IF EXISTS memory_index_jobs_identity_immutable ON memory_index_jobs")
    op.execute("DROP TRIGGER memory_index_jobs_scope ON memory_index_jobs")
    op.execute(
        "DROP TRIGGER IF EXISTS campaign_memory_indexes_identity_immutable "
        "ON campaign_memory_indexes"
    )
    op.execute("DROP TRIGGER memory_embeddings_immutable ON memory_embeddings")
    op.execute("DROP TRIGGER memory_embeddings_validate ON memory_embeddings")
    op.execute("DROP TRIGGER memory_documents_immutable_content ON memory_documents")
    op.execute("DROP TRIGGER memory_documents_scope ON memory_documents")
    op.execute("DROP TRIGGER memory_embedding_profiles_immutable ON memory_embedding_profiles")
    op.execute("DROP FUNCTION gandalfdnd_validate_memory_retrieval_item_scope()")
    op.execute("DROP FUNCTION gandalfdnd_validate_memory_retrieval_scope()")
    op.execute("DROP FUNCTION IF EXISTS gandalfdnd_protect_memory_index_job_identity()")
    op.execute("DROP FUNCTION IF EXISTS gandalfdnd_protect_campaign_memory_index_identity()")
    op.execute("DROP FUNCTION gandalfdnd_validate_memory_job_scope()")
    op.execute("DROP FUNCTION gandalfdnd_prevent_memory_audit_mutation()")
    op.execute("DROP FUNCTION gandalfdnd_validate_memory_embedding()")
    op.execute("DROP FUNCTION gandalfdnd_protect_memory_document_content()")
    op.execute("DROP FUNCTION gandalfdnd_validate_memory_document_scope()")
    op.drop_index(
        op.f("ix_memory_retrieval_items_retrieval_id"), table_name="memory_retrieval_items"
    )
    op.drop_index(
        op.f("ix_memory_retrieval_items_document_id"), table_name="memory_retrieval_items"
    )
    op.drop_table("memory_retrieval_items")
    op.drop_index(op.f("ix_memory_index_jobs_profile_id"), table_name="memory_index_jobs")
    op.drop_index(op.f("ix_memory_index_jobs_document_id"), table_name="memory_index_jobs")
    op.drop_index("ix_memory_index_jobs_claim", table_name="memory_index_jobs")
    op.drop_index(op.f("ix_memory_index_jobs_campaign_id"), table_name="memory_index_jobs")
    op.drop_table("memory_index_jobs")
    op.drop_index(op.f("ix_memory_embeddings_profile_id"), table_name="memory_embeddings")
    op.drop_index(op.f("ix_memory_embeddings_document_id"), table_name="memory_embeddings")
    op.drop_table("memory_embeddings")
    op.drop_index(op.f("ix_memory_retrievals_turn_id"), table_name="memory_retrievals")
    op.drop_index(op.f("ix_memory_retrievals_provider_call_id"), table_name="memory_retrievals")
    op.drop_index(op.f("ix_memory_retrievals_profile_id"), table_name="memory_retrievals")
    op.drop_index(op.f("ix_memory_retrievals_campaign_id"), table_name="memory_retrievals")
    op.drop_table("memory_retrievals")
    op.drop_index(
        "uq_memory_documents_turn_version_chunk",
        table_name="memory_documents",
        postgresql_where=sa.text("source_kind = 'turn'"),
    )
    op.drop_index(
        "uq_memory_documents_event_version_chunk",
        table_name="memory_documents",
        postgresql_where=sa.text("source_kind = 'event'"),
    )
    op.drop_index(op.f("ix_memory_documents_source_turn_id"), table_name="memory_documents")
    op.drop_index(op.f("ix_memory_documents_source_event_id"), table_name="memory_documents")
    op.drop_index(op.f("ix_memory_documents_quest_id"), table_name="memory_documents")
    op.drop_index(op.f("ix_memory_documents_npc_id"), table_name="memory_documents")
    op.drop_index(op.f("ix_memory_documents_location_id"), table_name="memory_documents")
    op.drop_index(op.f("ix_memory_documents_faction_id"), table_name="memory_documents")
    op.drop_index(op.f("ix_memory_documents_decision_id"), table_name="memory_documents")
    op.drop_index(op.f("ix_memory_documents_character_id"), table_name="memory_documents")
    op.drop_index(op.f("ix_memory_documents_campaign_id"), table_name="memory_documents")
    op.drop_index(
        "ix_memory_documents_campaign_active_sequence",
        table_name="memory_documents",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("memory_documents")
    op.drop_index(
        "uq_campaign_memory_indexes_one_active",
        table_name="campaign_memory_indexes",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(
        op.f("ix_campaign_memory_indexes_profile_id"), table_name="campaign_memory_indexes"
    )
    op.drop_index(
        op.f("ix_campaign_memory_indexes_campaign_id"), table_name="campaign_memory_indexes"
    )
    op.drop_table("campaign_memory_indexes")
    op.drop_table("memory_embedding_profiles")
    # ### end Alembic commands ###
